# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,    r: 'release', python: '3.12', gdal: '3.7.2', conda: false}
          - {os: windows-latest,  r: 'release', python: '3.11', gdal: '3.7.3', conda: false}
          - {os: windows-latest,  r: 'release', python: '3.11', gdal: '3.7.3', conda: true}
          - {os: ubuntu-latest,   r: 'devel', python: '3.12', gdal: '3.4.3', conda: false}
          - {os: ubuntu-latest,   r: 'release', python: '3.11', gdal: '3.4.3', conda: false}
          - {os: ubuntu-20.04,    r: '4.0', python: '3.10', gdal: '3.3.2', conda: false}

    env:
      R_SSURGOPORTAL_PYTHON_VERSION: ${{ matrix.config.python }}
      R_SSURGOPORTAL_GDAL_VERSION: ${{ matrix.config.gdal }}
      R_SSURGOPORTAL_USE_CONDAENV: ${{ matrix.config.conda }}
      R_SSIRG: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        if: runner.os == 'Windows' && matrix.config.conda
        with:
          python-version: ${{ matrix.config.python }}
          architecture: 'x64'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: conda-incubator/setup-miniconda@v2
        if: runner.os == 'Windows' && matrix.config.conda
        with:
          miniconda-version: "latest"
          activate-environment: r-ssurgoportal

      - name: Install rgeowheels (windows, virtualenv)
        if: runner.os == 'Windows' && !matrix.config.conda
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('brownag/rgeowheels')"

      - name: Install GDAL (windows, conda)
        if: runner.os == 'Windows' && matrix.config.conda
        run: |
          conda install -c conda-forge pip wheel numpy bottle jsonschema gdal

      - name: Install system and Python dependencies (ubuntu)
        if: runner.os != 'macOS' && runner.os != 'Windows'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt update
          sudo apt install gdal-bin libgdal-dev

      - name: Install system and Python dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gdal
#           brew tap-new $USER/local-gdal
#           brew extract --version=${{ matrix.config.gdal }} gdal $USER/local-gdal
#           brew install gdal@${{ matrix.config.gdal }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, local::., rstudio/reticulate
          needs: check

      - name: Install SSURGO-Portal
        run: |
          library(SSURGOPortal)
          install_ssurgo_portal()
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
